dist: precise
language: node_js
node_js:
  - "10"

services:
addons:
  mariadb: '10.0'
  
install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version
  - sudo mysql -e 'create database exit_db;'
  - sudo mysql -u root --password="" < tests/dump.sql
  - npm start &
script: bundle exec rake spec
env:
  global:
  

script:

  - node_modules/.bin/newman run tests/EXIT_API_testing.postman_collection.json -e tests/EXIT_API_testing.postman_environment.json --color auto --disable-unicode